### ISSUE TITLE
add info about server in header

### ISSUE THREAD

**Issue by mrRadik** [dotnetcrafted/cs-go-statistics#27]
branch: ServerQueries
api path: api/serverinfo

еще хотелось бы что бы по определенному интервалу эта инфа обновлялась. Например, можно использовать SignalR https://metanit.com/sharp/mvc5/16.2.php

**Comment by skvigl** [comment]
Привет, можно добавить примеры ответа сервера, если сервер включен/не включен?

**Comment by mrRadik** [comment]
testing OK on Live
