### ISSUE TITLE
"All Time" button

### ISSUE THREAD

**Issue by danilDelete** [dotnetcrafted/cs-go-statistics#7]
Add shortcut button to filter statisctics by the all time period since the first record.

![chrome_2019-12-20_14-22-41](https://user-images.githubusercontent.com/26994998/71244381-30aae880-2334-11ea-9616-b79c6782fb54.png)

**Comment by mayalex** [comment]
@Grimmino 
In implement the All Time Button function, you must call the submit form with the following parameters:
dateFrom: '',
dateTo: ''
